//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "78.3.3+g8158f7a+chromium-78.0.3904.87";
        public const int CEF_VERSION_MAJOR = 78;
        public const int CEF_COMMIT_NUMBER = 2086;
        public const string CEF_COMMIT_HASH = "8158f7af08e997fa76be7180dc211f809768ac6f";
        
        public const int CHROME_VERSION_MAJOR = 78;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 3904;
        public const int CHROME_VERSION_PATCH = 87;
        
        public const string CEF_API_HASH_UNIVERSAL = "3ad9591f7024619a1e2fd796c7ad51ae3a34abbb";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "3b8e38ae40c1a930227c6277c39dbc24081ccec1";
        public const string CEF_API_HASH_PLATFORM_MACOSX = "4a77f1908fabccdb01a2d3bdbede5ca09fbaa394";
        public const string CEF_API_HASH_PLATFORM_LINUX = "434da6be7db70fd90c4265118ac47ace4073c6ae";
    }
}
